Control
HotzoneAuto/diamond-auto pull request #27
Opened 2020-08-24 06:13 UTC by MengTC

Control: 0824

2020-08-24 06:30 UTC, mickeyouyou commented on modules/control/demo_control_component.cc
> +	if (veh_spd <= 0.1){ // TODO: 需更换成订阅canbus的车速数据
veh_spd = chassis_.speed_mps()

2020-08-24 06:34 UTC, mickeyouyou commented on modules/control/diamondauto_control_wheel_angle_real.h
> +static float front_encoder_angle_realtime = 0; // ǰ�ֱ�����˲ʱ����0~360 deg��
这个文件的编码格式检查下，应该是UTF8编码，否则在其中终端中文乱码，抑或用英文注释。

2020-08-24 06:44 UTC, mickeyouyou commented on modules/control/demo_control_component.cc
> +				cmd -> set_front_steering_target(10); //TODO 宗宝一起确定: 10%，待标定（目标角度暂时不用）
左负右正？确定下

2020-08-24 06:46 UTC, mickeyouyou commented on modules/control/diamondauto_control_pid.h
> +	veh_spd = chassis_->speed_mps();
显然，chassis_在这个文件是拿不到的

2020-08-24 06:48 UTC, mickeyouyou requested changes
Request changes

2020-08-24 06:57 UTC, mickeyouyou commented on modules/control/demo_control_component.cc
> +		//TODO: 消息发送，刷新
前轮方向的变化 请按照diamond_controller.cc中Streer方法执行以上指令。

2020-08-27 08:53 UTC, tao8687 approved these changes

2020-08-27 08:55 UTC, mickeyouyou approved these changes

2020-08-27 08:56 UTC, merged