Debug1028
HotzoneAuto/diamond-auto pull request #69
Opened 2020-10-29 10:05 UTC by tao8687

2020-10-29 10:08 UTC, mickeyouyou requested changes

2020-10-29 10:08 UTC, mickeyouyou commented on modules/control/conf/control_conf.pb.txt
> +drivemotor_flag: 2
@MengTC  why change flag here ?

2020-10-29 10:08 UTC, mickeyouyou commented on modules/control/control_component.cc
> +//pad_msg_.set_action(control_conf_.action());
remove this bug codes

2020-10-30 11:07 UTC, mickeyouyou approved these changes

2020-10-30 11:08 UTC, tao8687 reviewed
debug

2020-10-30 11:08 UTC, merged