Debug:xbox_one
HotzoneAuto/diamond-auto pull request #72
Opened 2020-11-09 07:31 UTC by tao8687

2020-11-10 09:51 UTC, mickeyouyou requested changes

2020-11-10 09:51 UTC, mickeyouyou commented on modules/canbus/tools/BUILD
> +	"@com_github_gflags_gflags//:gflags",
codes align

2020-11-10 09:51 UTC, mickeyouyou commented on modules/canbus/tools/xbox_one.cc
> +#include "modules/canbus/vehicle/vehicle_controller.h"
remove unused include and object.

2020-11-10 09:51 UTC, mickeyouyou commented on modules/canbus/tools/xbox_one.cc
> +using apollo::common::VehicleSignal;
remove unused include and object.

2020-11-10 09:51 UTC, mickeyouyou commented on modules/canbus/tools/xbox_one.cc
> +    control_command_.mutable_signal()->set_turn_signal(
diamond don't have turn signal message, so we can remove it.

2020-11-10 09:51 UTC, mickeyouyou commented on modules/canbus/tools/xbox_one.cc
> +  std::shared_ptr<Reader<Chassis>> chassis_reader_;
shared_ptr is point, so it's better to give default value like `nullptr`.

2020-11-10 11:37 UTC, tao8687 commented on modules/canbus/tools/xbox_one.cc
> +  std::shared_ptr<Reader<Chassis>> chassis_reader_;
std::shared_ptr<Reader<Chassis>> chassis_reader_=nullptr;
std::shared_ptr<Writer<ControlCommand>> control_command_writer_=nullptr;

2020-11-10 13:22 UTC, mickeyouyou commented on modules/canbus/tools/xbox_one.cc
> +  std::shared_ptr<Reader<Chassis>> chassis_reader_;
OK

2020-11-10 13:23 UTC, mickeyouyou commented
we also need an script to manager this executable build file.

2020-11-10 13:25 UTC, tao8687 reviewed
update

2020-11-11 02:34 UTC, mickeyouyou approved these changes

2020-11-11 06:57 UTC, merged